---
- name: Test with a file on Desktop
  hosts: VMs
  become: True
  tasks:
  - name: Ensure Desktop is reachable
    file:
      path: "/home/rj/Desktop"
      state: directory

  - name: Create the test file
    copy:
      dest: "/home/rj/Desktop/test.txt"
      content: "This is the test words!!!!!!"

  - name: add a text file to Desktop
    copy:
        dest: "/home/rj/Desktop/Ansible.txt"
        content: "I LOVE ANSIBLE!!!"
 
