---
- name: Update and upgrade all packages
  hosts: VMs
  become: true
  tasks:
    - name: Update package cache and upgrade all packages (CentOS/Red Hat)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update package cache and upgrade all packages (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
