---
- name: Delete everything in the Desktop folder
  hosts: localhost
  tasks:
    - name: Ensure all files and directories in Desktop are removed
      file:
        path: "/home/{{ ansible_user }}/Desktop/{{ item }}"
        state: absent
      loop: "{{ lookup('pipe', 'ls /home/{{ ansible_user }}/Desktop') | split('\n') }}"

